# Generated by Django 2.1.2 on 2018-10-14 09:16

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kirrurl',
            name='url',
            field=models.CharField(blank=True, max_length=220, null=True, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
